---
all:
  vars:
    ansible_user:               student
    ansible_python_interpreter: /usr/bin/python3
  children:  
    masters:
      hosts:
        master-1:
          ansible_host: master-1
        master-2:
          ansible_host: master-2
        master-3:
          ansible_host: master-3
      vars: 
        public_ip: "{{ lookup('dig', ansible_host) }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
    etcd:
        children:
            masters  
    nodes:
      hosts:
        node-1:
          ansible_host: node-1
          cni_host_subnet: "192.168.1.0/24"
        node-2:
          ansible_host: node-2
          cni_host_subnet: "192.168.2.0/24"
        node-3:
          ansible_host: node-3
          cni_host_subnet: "192.168.3.0/24"
      vars: 
        public_ip: "{{ lookup('dig', ansible_host) }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
