#!/bin/bash
set -uo pipefail

function now() {
    printf '%x' "$(date +%s%3N)"
}

# cd into the test directory
TEST_DIR=$(dirname "$(readlink -f "$0")")
pushd "${TEST_DIR}" >> /dev/null || exit 1

if [ -z ${1+x} ]; then
    echo "[-] missing lab-name, to run:"
    printf "\tsetup lab-name\n"
    exit 1
fi
LAB_ID=$1

if [ ! -f "${LAB_ID}/test.sh" ]; then
    echo "[-] ${LAB_ID} no test found"
    exit 1
fi

setup "${LAB_ID}"

# run this test
echo "[+] Testing ${LAB_ID}"
TEST_LOG="/tmp/$(now)_${LAB_ID}_test.log"
bash "${LAB_ID}/test.sh" 2>&1 | tee "${TEST_LOG}"
if [ $? -ne 0 ]; then
    echo "[-] Test failed"
    exit 1
fi

BROKE="deprecat|warn"
egrep -i "${BROKE}" "${TEST_LOG}" >> /dev/null
if [ $? -eq 0 ]; then
    echo "[-] Deprications or warnings found. Examine log:"
    echo "    ${TEST_LOG}"
    egrep --color -i "${BROKE}" "${TEST_LOG}"
fi

popd >> /dev/null || exit 1
echo "[+] Test complete"
