#!/bin/bash
set -uo pipefail

# cd into the test directory
TEST_DIR=$(dirname "$(readlink -f "$0")")
pushd "${TEST_DIR}" >> /dev/null || exit 1

if [ -z ${1+x} ]; then
    echo "[-] missing lab-name, to run:"
    printf "\tsetup lab-name\n"
    exit 1
fi
LAB_ID=$1

if [ ! -f "${LAB_ID}/test.sh" ]; then
    ls -al
    echo "[-] ${LAB_ID} no test found"
    exit 1
fi

setup "${LAB_ID}"

# run this test
echo "[+] Testing ${LAB_ID}"
bash "${LAB_ID}/test.sh"

popd >> /dev/null || exit 1
echo "[+] Test complete"
