apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clearml-nfs-smoke
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-clearml
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-clearml-test
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "echo 'ClearML NFS Test Successful' > /mnt/test.txt && cat /mnt/test.txt && sleep 5"]
    volumeMounts:
    - name: test-vol
      mountPath: /mnt
  volumes:
  - name: test-vol
    persistentVolumeClaim:
      claimName: clearml-nfs-smoke
