apiVersion: v1
kind: Pod
metadata:
  name: song-pod
spec:
  containers:
  - name: writer
    image: busybox:1.34.0
    command: ["/bin/sh", "-c"]
    args:
      - |
        i=1;
        while true; do
          echo "${i} bottles of beer on the wall, ${i} bottles of beer!" >> /wall/bottles.log;
          i=$((i+1));
          sleep 3;
        done
    volumeMounts:
    - name: wall-volume
      mountPath: /wall
  volumes:
  - name: wall-volume
    emptyDir: {}
