apiVersion: apps/v1
kind: Deployment
metadata:
  name: enter-sandman
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      band: metallica
  template:
    metadata:
      labels:
        app: nginx
        band: metallica
    spec:
      containers:
      - name: nginx
        image: nginx:1.18.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-base-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: georgeorwell
          mountPath: /var/www/static/1984.txt
          subPath: 1984.txt
      volumes:
      - name: nginx-base-config
        configMap:
          name: nginx-base-conf
      - name: georgeorwell
        configMap:
          name: nineteen-eighty-four
