apiVersion: v1
kind: Pod
metadata:
  name: visor-box
spec:
  runtimeClassName: runsc
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'while true; do echo "Running..."; sleep 1h; done']
