apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-backend
  name: nginx-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-backend
  template:
    metadata:
      labels:
        app: nginx-backend
    spec:
      containers:
      - image: nginxdemos/hello
        name: hello
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-backend
  name: nginx-backend
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-backend
  type: ClusterIP
