apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
labels:
  - pairs:
      variant: products
resources:
  - ../base
patches:
  - path: replicas.yaml
  - path: nodeport.yaml
images:
  - name: nginx
    newTag: 1.19.6
