apiVersion: v1
kind: Pod
metadata:
  name: podsecret1
spec:
  containers:
  - name: opensusepod
    image: opensuse/leap
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    volumeMounts:
    - name: secretmnt
      mountPath: "/mnt"
  volumes:
  - name: secretmnt
    secret:
      secretName: mysecret1
