apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-sa-r
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "replicasets", "deployments"]
  verbs: ["get", "watch", "list", "create", "apply", "edit"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privileged-sa-rb
subjects:
- kind: ServiceAccount
  name: privileged-sa
  namespace: default
roleRef:
  kind: Role
  name: privileged-sa-r
  apiGroup: rbac.authorization.k8s.io
