apiVersion: v1
kind: Pod
metadata:
  name: secured-cont
spec:
  securityContext:
    fsGroup: 2000
  containers:
  - name: secured-container
    image: busybox:1.34.0
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: secured-volume
      mountPath: /data/secured
  volumes:
    - name: secured-volume
      emptyDir: {}
