apiVersion: v1
kind: Pod
metadata:
  name: webservice01
spec:
  containers:
  - name: webby
    image: registry.gitlab.com/alta3research/webby
    ports:
    - name: web
      containerPort: 8888
      protocol: TCP

